<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>SpaceWizards.ConfigProvider</AssemblyName>
        <Version>1.0.0</Version>
        <Authors>Julian Giebel, Space Wizards</Authors>


        <!-- NuGet stuff. -->

        <PackageId>SpaceWizards.ConfigProvider</PackageId>
        <Authors>Julian Giebel, Space Wizards</Authors>
        <RepositoryType>Git</RepositoryType>
        <RepositoryUrl>https://github.com/space-wizards/ConfigProvider</RepositoryUrl>
        <PackageProjectUrl>https://github.com/space-wizards/ConfigProvider</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageTags>configuration</PackageTags>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Description>Database config provider.</Description>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
        <DebugType>embedded</DebugType>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>

        <!-- SourceLink -->
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
      <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All"/>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../LICENSE.txt" Pack="true" PackagePath="\"/>
        <None Include="../README.md" Pack="true" PackagePath="\"/>
        <None Include="../icon.png" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>
</Project>
